import Head from "next/head";
import { About, Footer, Header, Presentation, Portfolio } from "./sections";
import { Wrapper } from "./styles";

export default function Home() {
  return (
    <Wrapper>
      <Head>
        <title>Guilherme Santos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Presentation />
      <About />
      <Portfolio />
      <Footer />
    </Wrapper>
  );
}
